import os
import json
from typing import List


def parse_proxies(proxy_list: List[str]) -> List[str]:
    transformed_proxies = []
    for proxy in proxy_list:
        proxy_ip, proxy_port, proxy_user, proxy_pass = proxy.split(':')
        transformed_proxies.append(f"http://{proxy_user}:{proxy_pass}@{proxy_ip}:{proxy_port}")
    return transformed_proxies


PINECONE_API_KEY = "453fd009-bd51-4c9a-8e62-9900af7ea16f" or os.environ["PINECONE_API_KEY"]
PINECONE_INDEX = "topsonvici" or os.environ["PINECONE_INDEX"]
# HF_TOKEN = os.environ["HF_TOKEN"]
# HF_REPO = os.environ["HF_REPO"]
REPO_TYPE = "dataset"
TOPICS_LIST = json.loads(
"""
[
"Coral Reef Restoration Projects",
"E-commerce Trends 2023",
"Cryptocurrency Investment for Beginners",
"3D Printing Innovations",
"Introduction to NFTs and Digital Art",
"Zero Waste Lifestyle Tips",
"Underwater Photography Techniques",
"Mindfulness and Meditation Techniques",
"Building a Gaming PC from Scratch",
"Sport Psychology for Athletes",
"Plant-based Nutrition",
"Wildlife Conservation Efforts",
"Virtual Choirs and Online Music Collaboration",
"Modern Architecture and Design Trends",
"Introduction to Robotics for Kids",
"Filmmaking with Smartphones",
"Journey through the Solar System",
"Creating Digital Comics",
"Craft Beer Brewing at Home",
"Basics of Astrophotography",
"Yoga for Beginners",
"Breakdancing Techniques",
"High-Intensity Interval Training (HIIT)",
"Professional Networking Strategies",
"Voice Acting and Narration Techniques",
"Mixology and Cocktail Crafting",
"Mobile App Development with Flutter",
"Basics of 3D printing",
"Sports analytics and data science",
"Film making techniques",
"Fashion design and trends",
"Astronomy and space exploration",
"World cuisine cooking classes",
"Artificial organs and bioengineering",
"Photography composition and techniques",
"Music composition and theory",
"Mental health awareness",
"Mountain climbing expeditions",
"Organic farming methods",
"Personal finance management",
"Science fiction literature analysis",
"Architectural design concepts",
"Introduction to sociology",
"Vegetarian and vegan recipes",
"Global climate change initiatives",
"Ocean cleanup projects",
"Modern dance forms",
"Making of artisan chocolates",
"Essentials of cybersecurity",
"Psychology of social media",
"History of animation",
"Making homemade pasta",
"Origins of popular music genres",
"Culinary arts and techniques",
"History of comic books",
"Biographies of influential people",
"Historical events that shaped the modern world",
"The physics of space travel",
"Renewable energy sources and their impact",
"Understanding the human genome",
"The process of film-making from script to screen",
"The fundamentals of digital photography",
"Exploring different musical instruments",
"The development of artificial intelligence in healthcare",
"The history of aviation and future possibilities",
"The science behind weather forecasting",
"Learning foreign languages for beginners",
"The principles of effective public speaking",
"Cyber-ethics and digital citizenship",
"The impact of electric vehicles on the environment",
"Understanding stock markets and trading",
"Learning about diverse world cultures",
"How to write and publish a novel",
"The secrets of successful entrepreneurs",
"Practical self-defense techniques",
"Home cooking and recipes",
"Basic car maintenance",
"Smart home technology",
"Comparative religion studies",
"Basics of coding in Python",
"Microeconomics principles",
"Cultural anthropology",
"Photography and photo editing",
"Travel guides and tips",
"Fitness and personal training",
"Classical music appreciation",
"Modern art movements",
"Board game strategies",
"Home gardening and plant care",
"Wine tasting and sommelier courses",
"Animation and cartoon creation",
"Dog training and pet care",
"Solar power for homes",
"Making sourdough bread",
"Origins of the universe and Big Bang theory",
"Yoga and mental health",
"The impact of pollution on marine life",
"Building a personal brand",
"Rural vs. urban sustainability practices",
"The psychology of learning",
"Introduction to aerodynamics",
"The importance of biodiversity",
"Basics of genetic engineering",
"Volcanology and natural disasters",
"Indoor rock climbing techniques",
"Investigative journalism techniques",
"Space travel and the future of human colonization",
"Cooking and baking for beginners",
"Developing Augmented Reality applications",
"The impact of climate change on global ecosystems",
"Teaching language through immersion methods",
"The history and practice of yoga",
"Mountain biking and trail conservation",
"Building and programming robots",
"The science behind electric vehicles",
"Home brewing and coffee tasting",
"Stress management techniques",
"Aerodynamics in sports",
"Cardiovascular health and exercise",
"Basket weaving and textile art",
"Aquaponics and sustainable agriculture methods",
"History of the Olympic Games",
"Molecular gastronomy and culinary physics",
"Creative writing and storytelling",
"Parkour and freerunning basics",
"Vintage electronics restoration",
"Ethnobotany and plant uses",
"Skiing and snowboarding tips",
"Making electronic music",
"Bird watching and ornithology",
"Tabletop gaming culture",
"Base jumping and skydiving",
"Travel blogging tips",
"Career development strategies",
"The benefits of meditation",
"Understanding the global economy",
"The impact of AI on society",
"Cybersecurity threats and prevention",
"The basics of graphic design",
"The role of antibiotics in modern medicine",
"Introduction to astrophysics",
"Digital marketing strategies",
"The fundamentals of music theory",
"The development of vaccines",
"Understanding body language",
"Basic first aid and emergency response",
"Basics of sailing",
"Documenting daily life through photography",
"Basics of carpentry",
"Mountaineering and outdoor survival skills",
"Introduction to machine learning",
"Basics of digital painting",
"Developing Alexa Skills",
"Basics of blockchain technology",
"Improving memory and cognitive skills",
"Tailoring and sewing techniques",
"Learning the basics of chess",
"Wildlife photography",
"Principles of animation",
"The principles of minimalism",
"Travel photography",
"Understanding cryptocurrencies",
"Basics of copywriting",
"Getting started with podcasting",
"Navigating the freelance economy",
"The role of drones in modern agriculture",
"The psychology of advertising and consumer behavior",
"The history and culture of street art",
"Theoretical physics: Concepts and controversies",
"Documentary filmmaking and storytelling",
"The importance of water conservation",
"Cognitive behavioral therapy and mental health",
"Autonomous vehicles and transportation systems",
"The role of artificial intelligence in creative industries",
"Sustainable architecture and green buildings",
"Virtual teams and the future of work",
"The future of retail and e-commerce",
"Origins of classical music",
"Building mobile applications",
"Improving home energy efficiency",
"The art of photography",
"Exploring contemporary dance",
"Watercolor painting techniques",
"E-commerce business models",
"Creative writing workshops",
"Introduction to pottery",
"Advancements in biotechnology",
"E-commerce and digital marketing",
"AI in creative writing",
"Introduction to ethical fashion",
"Creating an indie film",
"The evolution of digital marketing",
"Space exploration and the Mars mission",
"Virtual and augmented reality in gaming",
"Machine learning in financial markets",
"Human rights issues around the world",
"The role of music in emotional health",
"The significance of public art",
"Social entrepreneurship and innovation",
"Photorealistic drawing techniques",
"DIY solar panel installation",
"History and culture of indigenous peoples",
"3D printing applications in medicine",
"Mobile photography tips and tricks",
"Freelancing and remote work strategies",
"Archaeological discoveries and methods",
"Physics of everyday phenomena",
"Nutrition and healthy eating habits",
"Exploring the universe through telescopes",
"Adventure sports and safety",
"Philosophy and critical thinking",
"Basics of renewable energy sources",
"Astronomy for beginners",
"Basic electrical engineering concepts",
"Making homemade cosmetics and skincare",
"Learn to play musical instruments",
"Basic principles of psychology",
"History of modern art",
"Cycling and bike maintenance",
"Agile and Scrum methodologies",
"Archery basics",
"Aquarium setup and maintenance",
"Baking bread and pastries",
"Tips for healthy eating",
"Coding for kids: Fun projects",
"Economic theories explained",
"Crafting with recyclable materials",
"World religions and spirituality",
"Composting and waste reduction",
"Fantasy football strategies",
"Comedic writing and performance",
"Educational content creation",
"Mixed martial arts techniques",
"Hiking and camping tips",
"Stand-up paddleboarding",
"History of the Renaissance art",
"Woodworking projects for the garden",
"Beginner's guide to bird watching",
"Marathon training schedules",
"Non-fiction creative writing",
"Learn to skateboard",
"Creating an online course",
"Tips for remote work productivity",
"Gardening in small spaces",
"The history and culture of hip hop music",
"The physics of sports and human movement",
"The role of NGOs in global development",
"3D printing and maker culture",
"Disaster preparedness and emergency response",
"Automotive repair and maintenance tips",
"The digital art revolution and tools",
"Learning a new language: Tips and tools",
"The benefits of community service",
"Understanding global warming and climate change"
]
""" or
    os.environ["TOPICS_LIST"])
PROXY_LIST = parse_proxies(json.loads(
"""
    []
"""
    or
    os.environ["PROXY_LIST"]))
IS_PROD = os.environ.get("IS_PROD", "false").lower() == "true"
CHECK_PROBABILITY = float(os.environ.get("CHECK_PROBABILITY", 0.1))
UPLOAD_BATCH_SIZE = int(os.environ.get("UPLOAD_BATCH_SIZE", 1024))
